### ISSUE TITLE
Fix exception that is thrown if you try to click and drag the baskets in the basket game

### ISSUE THREAD

**Issue by scott-parkhill** [CultureFoundryCA/WebModules#42]
```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at WebModules.Shared.DropArea.HandleDragEnter() in /home/parkhill/Documents/CultureFoundry/Coding/WebModules/WebModules/Shared/DropArea.razor:line 34
         at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
         at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'TIwfTfBBli9t0VNW3XCT1PvvZI7UmdrZ90QeJkuq0o0'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at WebModules.Shared.DropArea.HandleDragEnter() in /home/parkhill/Documents/CultureFoundry/Coding/WebModules/WebModules/Shared/DropArea.razor:line 34
         at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
         at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
```

**Comment by gian7sm** [comment]
@scott-parkhill , this was fixed by making basket non-draggable, thanks for catching this bug.
